# configs/entities/customer.yaml
schema_version: 1
entity_name: customer

source:
  topic: insightflow.public.customer

business_keys: customer_id


columns:

  customer_id:
    datatype: string
    nullable: false
    business_key: true

  customer_name:
    datatype: string
    nullable: false

  customer_status:
    datatype: string
    nullable: false
    allowed_values:
      - ACTIVE
      - INACTIVE

  industry:
    datatype: string
    nullable: true

  customer_size:
    datatype: string
    nullable: true

  customer_tier:
    datatype: string
    nullable: true
    allowed_values:
      - Gold
      - Platinum
      - Silver
      - Diamond
      - GOLD
      - LOCAL TESTING

  customer_start_date:
    datatype: date
    nullable: true
    source_format: epoch_days

  customer_end_date:
    datatype: date
    nullable: true
    source_format: epoch_days

  created_timestamp:
    datatype: timestamp
    nullable: false
    source_format: epoch_micros

  updated_timestamp:
    datatype: timestamp
    nullable: false
    source_format: epoch_micros
  

system_columns:

  op:
    datatype: string
    nullable: false

  ts_ms:
    datatype: timestamp
    nullable: false
    source_format: epoch_millis


cdc:

  operation_column: op

  event_timestamp_column: ts_ms

  supported_operations:
    - c
    - u
    - d
    - r
scd:
  type: 2
  tracking_columns:
    - customer_name
    - customer_status
    - industry
    - customer_size
    - customer_tier